version: '3'
services:
    db:
        build:
            context: ./Docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: golangDB
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        container_name: golang_db
        ports:
            - "3306:3306"
        tty: true
        volumes:
            - my-datavolume:/var/lib/mysql
    app:
        build:
            context: ./Docker/Golang
        volumes:
            - "./:/go/src/github.com/goRESTapi"
        container_name: golang_app
        ports:
            - "9090:9090"
        tty: true
        depends_on:
            - db
volumes:
    my-datavolume: