version: '3'
services:
    db:
        build:
            context: ./Docker/postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: golangDB
        ports:
            - "5432:5432"
        tty: true
        volumes:
            - db-data:/var/lib/postgresql/data
    app:
        build:
            context: ./Docker/Golang
        volumes:
            - "./:/go/src/github.com/goRESTapi"
        container_name: golang_app
        ports:
            - "9090:9090"
        tty: true
        depends_on:
            - db

volumes:
    db-data: